apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ghcr.io/fateh-bensaali/myapp:6d0c05303ec7d2dfc04968e411fae413abe4f694
        ports:
        - containerPort: 5000
