apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ghcr.io/fateh-bensaali/myapp:c1f86bb83903b15bdb3a4434e18afa5e4f6e75e7
        ports:
        - containerPort: 5000
