apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ghcr.io/fateh-bensaali/myapp:452859bec265fa84035e0f43bd68b83d74d3ff59
        ports:
        - containerPort: 5000
