apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: dev-
images:
- name: postgres
  newName: ghcr.io/Fateh-Bensaali/benslab
  newTag: 78852e8c0dc372bebac58b92678d2d5cd10c11bc
