apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: dev-
images:
- name: postgres
  newName: ghcr.io/fateh-bensaali/benslab
  newTag: f1dec74140451ab5135989992dcc12409414d38e
