apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: dev-
images:
- name: postgres
  newName: ghcr.io/Fateh-Bensaali/benslab
  newTag: 08b4d92039910053e02893e8e75a881021260e63
